package com.siu.android.dondusang.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.siu.android.dondusang.R;
import com.siu.android.dondusang.util.DateUtils;

/**
 * Entity mapped to table centers.
 */
public class Center implements java.io.Serializable {

    private Long id;
    private String city;
    private String description;
    private Double latitude;
    private Double longitude;
    private String phone;
    private String email;
    private String region;
    private java.util.Date date;
    private java.util.Date start;
    private java.util.Date end;
    private String type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Center() {
    }

    public Center(Long id) {
        this.id = id;
    }

    public Center(Long id, String city, String description, Double latitude, Double longitude, String phone, String email, String region, java.util.Date date, java.util.Date start, java.util.Date end, String type) {
        this.id = id;
        this.city = city;
        this.description = description;
        this.latitude = latitude;
        this.longitude = longitude;
        this.phone = phone;
        this.email = email;
        this.region = region;
        this.date = date;
        this.start = start;
        this.end = end;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public java.util.Date getStart() {
        return start;
    }

    public void setStart(java.util.Date start) {
        this.start = start;
    }

    public java.util.Date getEnd() {
        return end;
    }

    public void setEnd(java.util.Date end) {
        this.end = end;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    public boolean isPermanent() {
        return null != region;
    }

    public boolean isTemporal() {
        return null != type;
    }

    public String getTitle() {
        if (isPermanent()) {
            return region;
        }

        return "Centre mobile";
    }

    public int getMarkerId() {
        return isPermanent() ? R.drawable.pin_blue : R.drawable.pin_red;

//        if (isPermanent()) {
//            return R.drawable.pin_blue;
//        }
//
//        if (type.equals("M")) {
//            return R.drawable.ic_map_marker_mix;
//        }
//
//        if (type.equals("S")) {
//            return R.drawable.ic_map_marker_red;
//        }
//
//        if (type.equals("P")) {
//            return R.drawable.ic_map_marker_yellow;
//        }
//
//        Log.w(getClass().getName(), "Unknown marker color");
//        return R.drawable.ic_map_marker_blue;
    }

    public String getSubtitle() {
        if (isPermanent()) {
            return "Situé à " + city;
        }

        return "Le " + DateUtils.formatAsFull(date) + ", à " + city;
    }
    // KEEP METHODS END

}
